name: vapermovil
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  intl: ^0.18.1
  cached_network_image: ^3.3.0
  image_picker: ^1.0.7
  file_picker: ^8.0.0
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icono-inicio.png"
  adaptive_icon_background: "#D3D3D3"
  adaptive_icon_foreground: "assets/images/icono-inicio.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/vaper_logo.png
    - assets/images/icono-inicio.png

dependency_overrides:
  file_picker: ^8.0.0
